eureka:
  # server itself should not be registered as a client
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost

#spring:
#  security:
#    user:
#      name: eureka
#      password: password

server:
  # default port for eureka server
  port: 8761

spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0